theme: jekyll-theme-cayman
title: GenAI Roadmap for Juniors
description: A minimal, beginner-friendly roadmap for juniors and career switchers entering the world of Generative AI.
show_downloads: false
